[package]
name = "ion-win"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
redb = "2.0"
glob = "0.3"
crossterm = "0.27"
ctrlc = "3"
regex = "1"
unicode-segmentation = "1.12"
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.10"
zip = { version = "8", default-features = false, features = ["deflate", "time"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Threading", "Win32_System_Console", "Win32_Foundation"] }
windows = { version = "0.52", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
